name: Deploy and Run V2
env:
  REPO_NAME: ${{github.event.repository.name}}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
     
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -f ./Dockerfile -t ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:latest .
        docker push ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: test  # Ajusta si tienes variables en entornos específicos
    defaults:
      run:
        shell: bash
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Container Instance
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        location: brazilsouth
        name: flask-project
        image: ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:latest
        dns-name-label: flask-project-${{ github.run_id }}-${{ github.run_attempt }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 5000
        cpu: 1
        memory: 1
    
    - name: Logout from Azure
      run: az logout